# Generated by Django 3.2 on 2022-01-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidation',
            name='email',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
    ]
