# Generated by Django 3.2 on 2022-01-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userregistration_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='employee',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='repairEmployee',
            field=models.BooleanField(default=False, verbose_name='是否为维修员'),
        ),
    ]
