# Generated by Django 3.2 on 2022-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_emailcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0, verbose_name='用户id')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('email_code', models.CharField(max_length=8, unique=True, verbose_name='代码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
        ),
    ]
